export const THEMES = [
  {
    id: 'luxury-noir-gold',
    name: '⚜️ Luxury Noir & Gold',
    description: 'Alta cocina y gourmet. Carbón profundo con acentos dorados, tipografía Playfair refinada y bordes dorados delgados. Para restaurantes premium y fine dining.',
    emoji: '⚜️',
    previewBg: '#0a0a0c',
    previewAccent: '#c9a84c',
    previewCard: '#141318',
    config: {
      theme: 'dark',
      primaryColor: '#c9a84c',
      backgroundColor: '#0a0a0c',
      navBarBgColor: '#0a0a0c',
      navBarTextColor: '#c9a84c',
      fontFamily: 'Playfair Display',
      fullWidthBackground: true,
      cardBackgroundColor: '#141318',
      cardBackgroundOpacity: '95',
      cardBlur: '0',
      showCardBorder: true,
      cardBorderWidth: '1',
      cardBorderColor: '#2a2318',
      cardBorderRadius: '4',
      cardMarginTop: '0', cardMarginRight: '0', cardMarginBottom: '16', cardMarginLeft: '0',
      cardPaddingTop: '16', cardPaddingRight: '16', cardPaddingBottom: '16', cardPaddingLeft: '16',
      cardLayout: 'row-img-right',
      gridColumns: '1',
      titleFontSize: '17',
      titleColor: '#f5f0e8',
      titleUppercase: true,
      titleLetterSpacing: '0.1',
      descFontSize: '12',
      descColor: '#8a7e6a',
      priceFontSize: '16',
      priceColor: '#c9a84c',
      priceLetterSpacing: '0.05',
      productImageWidth: '0',
      productImageRadius: '2px',
      productImageHeight: '90',
      cardSeparatorStyle: 'none',
      addButtonColor: '#c9a84c',
      addButtonTextColor: '#0a0a0c',
      addButtonRadius: '2',
      addButtonWidth: 'auto',
      addButtonFontSize: '12',
      subcatFontSize: '24',
      subcatColor: '#c9a84c',
      subcatAlignment: 'center',
      subcatBgColor: '#0a0a0c',
      subcatTextColor: '#c9a84c',
      bgOverlayEnabled: false,
      showItemIndexBadge: false,
      categoryCardBgColor: '#141318',
      categoryCardTextColor: '#c9a84c',
      cardShadow: '0 4px 20px rgba(201,168,76,0.08)',
      welcomeCardBgColor: '#141318',
      welcomeTextColor: '#c9a84c',
      categoriesGridCols: '2',
    }
  },
  {
    id: 'minimalist-japanese',
    name: '🍣 Minimalist Japanese',
    description: 'Sushi, ramen y sake. Fondo blanco piedra, acento rojo carmesí, tipografía limpia con espaciados amplios. Wabi-sabi sofisticado.',
    emoji: '🍣',
    previewBg: '#f7f5f2',
    previewAccent: '#c0392b',
    previewCard: '#ffffff',
    config: {
      theme: 'light',
      primaryColor: '#c0392b',
      backgroundColor: '#f7f5f2',
      navBarBgColor: '#1c1c1c',
      navBarTextColor: '#f7f5f2',
      fontFamily: 'Outfit',
      fullWidthBackground: true,
      cardBackgroundColor: '#ffffff',
      cardBackgroundOpacity: '100',
      cardBlur: '0',
      showCardBorder: true,
      cardBorderWidth: '1',
      cardBorderColor: '#e8e4de',
      cardBorderRadius: '0',
      cardMarginTop: '0', cardMarginRight: '0', cardMarginBottom: '1', cardMarginLeft: '0',
      cardPaddingTop: '18', cardPaddingRight: '16', cardPaddingBottom: '18', cardPaddingLeft: '16',
      cardLayout: 'row-traditional',
      gridColumns: '1',
      titleFontSize: '15',
      titleColor: '#1c1c1c',
      titleUppercase: false,
      titleLetterSpacing: '0.06',
      descFontSize: '12',
      descColor: '#6b6560',
      priceFontSize: '15',
      priceColor: '#c0392b',
      priceLetterSpacing: '0',
      productImageWidth: '0',
      productImageRadius: '2px',
      productImageHeight: '75',
      cardSeparatorStyle: 'dotted',
      cardSeparatorColor: '#d4cfc8',
      cardSeparatorHeight: '1',
      cardSeparatorWidth: '100',
      addButtonColor: '#1c1c1c',
      addButtonTextColor: '#f7f5f2',
      addButtonRadius: '0',
      addButtonWidth: 'auto',
      addButtonFontSize: '11',
      subcatFontSize: '13',
      subcatColor: '#1c1c1c',
      subcatAlignment: 'left',
      subcatBgColor: '#f7f5f2',
      subcatTextColor: '#1c1c1c',
      bgOverlayEnabled: false,
      showItemIndexBadge: false,
      categoryCardBgColor: '#1c1c1c',
      categoryCardTextColor: '#f7f5f2',
      cardShadow: 'none',
      welcomeCardBgColor: '#ffffff',
      welcomeTextColor: '#1c1c1c',
      categoriesGridCols: '2',
    }
  },
  {
    id: 'rustic-italian-trattoria',
    name: '🍷 Rustic Italian Trattoria',
    description: 'Pastas, pizzas al horno de leña y vinos. Terracota profundo, crema de trigo, verde oliva. Tipografía Lora con separadores decorativos y sensación acogedora.',
    emoji: '🍷',
    previewBg: '#fdf8f1',
    previewAccent: '#9b2335',
    previewCard: '#ffffff',
    config: {
      theme: 'light',
      primaryColor: '#9b2335',
      backgroundColor: '#fdf8f1',
      navBarBgColor: '#3d1f0f',
      navBarTextColor: '#f5e6c8',
      fontFamily: 'Lora',
      fullWidthBackground: true,
      cardBackgroundColor: '#ffffff',
      cardBackgroundOpacity: '100',
      cardBlur: '0',
      showCardBorder: true,
      cardBorderWidth: '1',
      cardBorderColor: '#e8dcc8',
      cardBorderRadius: '8',
      cardMarginTop: '0', cardMarginRight: '0', cardMarginBottom: '14', cardMarginLeft: '0',
      cardPaddingTop: '16', cardPaddingRight: '14', cardPaddingBottom: '16', cardPaddingLeft: '14',
      cardLayout: 'row-img-left',
      gridColumns: '1',
      titleFontSize: '17',
      titleColor: '#2c1810',
      titleUppercase: false,
      titleLetterSpacing: '0',
      descFontSize: '13',
      descColor: '#7a6550',
      priceFontSize: '16',
      priceColor: '#9b2335',
      productImageWidth: '0',
      productImageRadius: '6px',
      productImageHeight: '85',
      cardSeparatorStyle: 'none',
      addButtonColor: '#9b2335',
      addButtonTextColor: '#ffffff',
      addButtonRadius: '20',
      addButtonWidth: 'auto',
      addButtonFontSize: '13',
      subcatFontSize: '22',
      subcatColor: '#3d1f0f',
      subcatAlignment: 'left',
      subcatBgColor: '#fdf8f1',
      subcatTextColor: '#3d1f0f',
      bgOverlayEnabled: false,
      showItemIndexBadge: false,
      categoryCardBgColor: '#3d1f0f',
      categoryCardTextColor: '#f5e6c8',
      cardShadow: '0 2px 12px rgba(44,24,16,0.08)',
      welcomeCardBgColor: '#ffffff',
      welcomeTextColor: '#9b2335',
      categoriesGridCols: '2',
    }
  },
  {
    id: 'eco-healthy-bistro',
    name: '🌿 Eco Healthy Bistro',
    description: 'Bowls, jugos, vegano y saludable. Verde salvia oscuro con crema de lino, tipografía Outfit redondeada. Orgánico, fresco y legible.',
    emoji: '🌿',
    previewBg: '#f2f7f0',
    previewAccent: '#3d7a5a',
    previewCard: '#ffffff',
    config: {
      theme: 'light',
      primaryColor: '#3d7a5a',
      backgroundColor: '#f2f7f0',
      navBarBgColor: '#1e3d2f',
      navBarTextColor: '#e8f5ec',
      fontFamily: 'Outfit',
      fullWidthBackground: true,
      cardBackgroundColor: '#ffffff',
      cardBackgroundOpacity: '100',
      cardBlur: '0',
      showCardBorder: false,
      cardBorderRadius: '20',
      cardMarginTop: '0', cardMarginRight: '6', cardMarginBottom: '12', cardMarginLeft: '6',
      cardPaddingTop: '0', cardPaddingRight: '0', cardPaddingBottom: '12', cardPaddingLeft: '0',
      cardLayout: 'col-standard',
      gridColumns: '2',
      titleFontSize: '15',
      titleColor: '#1e3d2f',
      titleUppercase: false,
      titleLetterSpacing: '0',
      descFontSize: '12',
      descColor: '#5a7a68',
      priceFontSize: '15',
      priceColor: '#3d7a5a',
      productImageWidth: '0',
      productImageRadius: '16px',
      productImageHeight: '150',
      cardSeparatorStyle: 'none',
      addButtonColor: '#3d7a5a',
      addButtonTextColor: '#ffffff',
      addButtonRadius: '50',
      addButtonWidth: '100',
      addButtonFontSize: '13',
      subcatFontSize: '20',
      subcatColor: '#1e3d2f',
      subcatAlignment: 'left',
      subcatBgColor: '#e8f5ec',
      subcatTextColor: '#1e3d2f',
      bgOverlayEnabled: false,
      showItemIndexBadge: false,
      categoryCardBgColor: '#1e3d2f',
      categoryCardTextColor: '#e8f5ec',
      cardShadow: '0 4px 16px rgba(61,122,90,0.1)',
      welcomeCardBgColor: '#ffffff',
      welcomeTextColor: '#3d7a5a',
      categoriesGridCols: '2',
    }
  },
  {
    id: 'pink-paris-patisserie',
    name: '🌸 Pink Paris Patisserie',
    description: 'Repostería fina, macarons y pastelería de lujo. Rosa algodón de azúcar con oro rosa, tipografía Playfair Display romántica y tarjetas con brillo suave.',
    emoji: '🌸',
    previewBg: '#fdf2f8',
    previewAccent: '#be185d',
    previewCard: '#ffffff',
    config: {
      theme: 'light',
      primaryColor: '#be185d',
      backgroundColor: '#fdf2f8',
      navBarBgColor: '#fce7f3',
      navBarTextColor: '#9d174d',
      fontFamily: 'Playfair Display',
      fullWidthBackground: true,
      cardBackgroundColor: '#ffffff',
      cardBackgroundOpacity: '100',
      cardBlur: '0',
      showCardBorder: true,
      cardBorderWidth: '1',
      cardBorderColor: '#fce7f3',
      cardBorderRadius: '24',
      cardMarginTop: '0', cardMarginRight: '6', cardMarginBottom: '16', cardMarginLeft: '6',
      cardPaddingTop: '0', cardPaddingRight: '0', cardPaddingBottom: '14', cardPaddingLeft: '0',
      cardLayout: 'col-standard',
      gridColumns: '2',
      titleFontSize: '15',
      titleColor: '#831843',
      titleUppercase: false,
      titleLetterSpacing: '0',
      descFontSize: '11',
      descColor: '#c084a4',
      priceFontSize: '15',
      priceColor: '#be185d',
      productImageWidth: '0',
      productImageRadius: '18px',
      productImageHeight: '145',
      cardSeparatorStyle: 'none',
      addButtonColor: '#be185d',
      addButtonTextColor: '#ffffff',
      addButtonRadius: '50',
      addButtonWidth: '100',
      addButtonFontSize: '12',
      subcatFontSize: '20',
      subcatColor: '#9d174d',
      subcatAlignment: 'center',
      subcatBgColor: '#fce7f3',
      subcatTextColor: '#9d174d',
      bgOverlayEnabled: false,
      showItemIndexBadge: false,
      categoryCardBgColor: '#fce7f3',
      categoryCardTextColor: '#831843',
      cardShadow: '0 6px 24px rgba(190,24,93,0.1)',
      welcomeCardBgColor: '#ffffff',
      welcomeTextColor: '#be185d',
      categoriesGridCols: '2',
    }
  },
  {
    id: 'cyberpunk-street-food',
    name: '⚡ Cyberpunk Street Food',
    description: 'Hamburgueserías urbanas, food trucks y comida nocturna. Negro puro con neón rosa y cian, tipografía compacta y alto contraste. Energía brutal.',
    emoji: '⚡',
    previewBg: '#030305',
    previewAccent: '#f43f5e',
    previewCard: '#0d0d12',
    config: {
      theme: 'dark',
      primaryColor: '#f43f5e',
      backgroundColor: '#030305',
      navBarBgColor: '#030305',
      navBarTextColor: '#f43f5e',
      fontFamily: 'Outfit',
      fullWidthBackground: true,
      cardBackgroundColor: '#0d0d12',
      cardBackgroundOpacity: '98',
      cardBlur: '0',
      showCardBorder: true,
      cardBorderWidth: '1',
      cardBorderColor: '#1f1f2e',
      cardBorderRadius: '0',
      cardMarginTop: '0', cardMarginRight: '0', cardMarginBottom: '2', cardMarginLeft: '0',
      cardPaddingTop: '14', cardPaddingRight: '14', cardPaddingBottom: '14', cardPaddingLeft: '14',
      cardLayout: 'row-img-left',
      gridColumns: '1',
      titleFontSize: '16',
      titleColor: '#ffffff',
      titleUppercase: true,
      titleLetterSpacing: '0.05',
      descFontSize: '12',
      descColor: '#6b7280',
      priceFontSize: '16',
      priceColor: '#06b6d4',
      productImageWidth: '0',
      productImageRadius: '0',
      productImageHeight: '80',
      cardSeparatorStyle: 'none',
      addButtonColor: '#f43f5e',
      addButtonTextColor: '#030305',
      addButtonRadius: '0',
      addButtonWidth: 'auto',
      addButtonFontSize: '12',
      subcatFontSize: '18',
      subcatColor: '#06b6d4',
      subcatAlignment: 'left',
      subcatBgColor: '#0d0d12',
      subcatTextColor: '#06b6d4',
      bgOverlayEnabled: false,
      showItemIndexBadge: true,
      itemIndexBadgeBg: '#f43f5e',
      itemIndexBadgeColor: '#030305',
      itemIndexBadgeSize: '32',
      categoryCardBgColor: '#0d0d12',
      categoryCardTextColor: '#f43f5e',
      cardShadow: '0 0 20px rgba(244,63,94,0.15)',
      welcomeCardBgColor: '#0d0d12',
      welcomeTextColor: '#f43f5e',
      categoriesGridCols: '2',
    }
  },
  {
    id: 'highend-steakhouse',
    name: '🥩 High-End Steakhouse',
    description: 'Cortes premium, carnes maduradas y grill de autor. Gris pizarra oscuro con burdeos profundo. Fuerte, imponente y masculino.',
    emoji: '🥩',
    previewBg: '#0c1117',
    previewAccent: '#9f1239',
    previewCard: '#141b24',
    config: {
      theme: 'dark',
      primaryColor: '#9f1239',
      backgroundColor: '#0c1117',
      navBarBgColor: '#060a0e',
      navBarTextColor: '#e2e8f0',
      fontFamily: 'Montserrat',
      fullWidthBackground: true,
      cardBackgroundColor: '#141b24',
      cardBackgroundOpacity: '100',
      cardBlur: '0',
      showCardBorder: true,
      cardBorderWidth: '1',
      cardBorderColor: '#1e2a38',
      cardBorderRadius: '6',
      cardMarginTop: '0', cardMarginRight: '0', cardMarginBottom: '14', cardMarginLeft: '0',
      cardPaddingTop: '0', cardPaddingRight: '0', cardPaddingBottom: '14', cardPaddingLeft: '0',
      cardLayout: 'col-standard',
      gridColumns: '1',
      titleFontSize: '18',
      titleColor: '#f1f5f9',
      titleUppercase: true,
      titleLetterSpacing: '0.08',
      descFontSize: '13',
      descColor: '#64748b',
      priceFontSize: '18',
      priceColor: '#9f1239',
      productImageWidth: '0',
      productImageRadius: '4px',
      productImageHeight: '220',
      cardSeparatorStyle: 'none',
      addButtonColor: '#9f1239',
      addButtonTextColor: '#ffffff',
      addButtonRadius: '4',
      addButtonWidth: '100',
      addButtonFontSize: '13',
      subcatFontSize: '22',
      subcatColor: '#9f1239',
      subcatAlignment: 'center',
      subcatBgColor: '#0c1117',
      subcatTextColor: '#e2e8f0',
      bgOverlayEnabled: false,
      showItemIndexBadge: false,
      categoryCardBgColor: '#141b24',
      categoryCardTextColor: '#e2e8f0',
      cardShadow: '0 8px 30px rgba(0,0,0,0.4)',
      welcomeCardBgColor: '#141b24',
      welcomeTextColor: '#9f1239',
      categoriesGridCols: '1',
    }
  },
  {
    id: 'cozy-bakery-cafe',
    name: '☕ Cozy Bakery & Café',
    description: 'Cafetería artesanal y repostería casera. Caramelo tostado, vainilla suave y madera clara. Acogedor, aromático y hogareño.',
    emoji: '☕',
    previewBg: '#fdf6ee',
    previewAccent: '#92400e',
    previewCard: '#fff9f0',
    config: {
      theme: 'light',
      primaryColor: '#92400e',
      backgroundColor: '#fdf6ee',
      navBarBgColor: '#451a03',
      navBarTextColor: '#fef3c7',
      fontFamily: 'Lora',
      fullWidthBackground: true,
      cardBackgroundColor: '#fff9f0',
      cardBackgroundOpacity: '100',
      cardBlur: '0',
      showCardBorder: true,
      cardBorderWidth: '1',
      cardBorderColor: '#f3e4cc',
      cardBorderRadius: '16',
      cardMarginTop: '0', cardMarginRight: '6', cardMarginBottom: '14', cardMarginLeft: '6',
      cardPaddingTop: '0', cardPaddingRight: '0', cardPaddingBottom: '12', cardPaddingLeft: '0',
      cardLayout: 'col-standard',
      gridColumns: '2',
      titleFontSize: '15',
      titleColor: '#451a03',
      titleUppercase: false,
      titleLetterSpacing: '0',
      descFontSize: '12',
      descColor: '#92785a',
      priceFontSize: '15',
      priceColor: '#92400e',
      productImageWidth: '0',
      productImageRadius: '12px',
      productImageHeight: '140',
      cardSeparatorStyle: 'none',
      addButtonColor: '#92400e',
      addButtonTextColor: '#fef3c7',
      addButtonRadius: '50',
      addButtonWidth: '100',
      addButtonFontSize: '12',
      subcatFontSize: '20',
      subcatColor: '#451a03',
      subcatAlignment: 'left',
      subcatBgColor: '#fdf6ee',
      subcatTextColor: '#451a03',
      bgOverlayEnabled: false,
      showItemIndexBadge: false,
      categoryCardBgColor: '#451a03',
      categoryCardTextColor: '#fef3c7',
      cardShadow: '0 4px 14px rgba(146,64,14,0.1)',
      welcomeCardBgColor: '#fff9f0',
      welcomeTextColor: '#92400e',
      categoriesGridCols: '2',
    }
  },
  {
    id: 'art-deco-cocktail-bar',
    name: '🍸 Art Deco Cocktail Bar',
    description: 'Coctelería de autor y bar premium. Verde esmeralda rico con latón dorado. Glassmorphism elegante estilo Gatsby de los años 20.',
    emoji: '🍸',
    previewBg: '#021a12',
    previewAccent: '#ca8a04',
    previewCard: '#052e1a',
    config: {
      theme: 'dark',
      primaryColor: '#ca8a04',
      backgroundColor: '#021a12',
      navBarBgColor: '#010e09',
      navBarTextColor: '#ca8a04',
      fontFamily: 'Playfair Display',
      fullWidthBackground: true,
      cardBackgroundColor: '#052e1a',
      cardBackgroundOpacity: '80',
      cardBlur: '12',
      showCardBorder: true,
      cardBorderWidth: '1',
      cardBorderColor: '#0d5c35',
      cardBorderRadius: '8',
      cardMarginTop: '0', cardMarginRight: '0', cardMarginBottom: '16', cardMarginLeft: '0',
      cardPaddingTop: '16', cardPaddingRight: '16', cardPaddingBottom: '16', cardPaddingLeft: '16',
      cardLayout: 'row-img-right',
      gridColumns: '1',
      titleFontSize: '17',
      titleColor: '#fef9e7',
      titleUppercase: true,
      titleLetterSpacing: '0.1',
      descFontSize: '12',
      descColor: '#6ee7b7',
      priceFontSize: '16',
      priceColor: '#ca8a04',
      productImageWidth: '0',
      productImageRadius: '4px',
      productImageHeight: '85',
      cardSeparatorStyle: 'none',
      addButtonColor: '#ca8a04',
      addButtonTextColor: '#021a12',
      addButtonRadius: '4',
      addButtonWidth: 'auto',
      addButtonFontSize: '12',
      subcatFontSize: '22',
      subcatColor: '#ca8a04',
      subcatAlignment: 'center',
      subcatBgColor: '#021a12',
      subcatTextColor: '#ca8a04',
      bgOverlayEnabled: false,
      showItemIndexBadge: false,
      categoryCardBgColor: '#052e1a',
      categoryCardTextColor: '#fef9e7',
      cardShadow: '0 8px 32px rgba(0,0,0,0.5)',
      welcomeCardBgColor: '#052e1a',
      welcomeTextColor: '#ca8a04',
      categoriesGridCols: '2',
    }
  },
  {
    id: 'beach-club-lounge',
    name: '🏖️ Beach Club & Lounge',
    description: 'Mariscos, ceviches y terraza frente al mar. Azul turquesa vibrante, blanco arena y coral suave. Fresco, tropical y premium.',
    emoji: '🏖️',
    previewBg: '#f0faff',
    previewAccent: '#0891b2',
    previewCard: '#ffffff',
    config: {
      theme: 'light',
      primaryColor: '#0891b2',
      backgroundColor: '#f0faff',
      navBarBgColor: '#0c4a6e',
      navBarTextColor: '#e0f2fe',
      fontFamily: 'Inter',
      fullWidthBackground: true,
      cardBackgroundColor: '#ffffff',
      cardBackgroundOpacity: '100',
      cardBlur: '0',
      showCardBorder: false,
      cardBorderRadius: '24',
      cardMarginTop: '0', cardMarginRight: '6', cardMarginBottom: '14', cardMarginLeft: '6',
      cardPaddingTop: '0', cardPaddingRight: '0', cardPaddingBottom: '14', cardPaddingLeft: '0',
      cardLayout: 'col-standard',
      gridColumns: '2',
      titleFontSize: '15',
      titleColor: '#0c4a6e',
      titleUppercase: false,
      titleLetterSpacing: '0',
      descFontSize: '12',
      descColor: '#4a7fa0',
      priceFontSize: '16',
      priceColor: '#0891b2',
      productImageWidth: '0',
      productImageRadius: '18px',
      productImageHeight: '150',
      cardSeparatorStyle: 'none',
      addButtonColor: '#0891b2',
      addButtonTextColor: '#ffffff',
      addButtonRadius: '50',
      addButtonWidth: '100',
      addButtonFontSize: '13',
      subcatFontSize: '18',
      subcatColor: '#0c4a6e',
      subcatAlignment: 'center',
      subcatBgColor: '#e0f2fe',
      subcatTextColor: '#0c4a6e',
      bgOverlayEnabled: false,
      showItemIndexBadge: false,
      categoryCardBgColor: '#0c4a6e',
      categoryCardTextColor: '#e0f2fe',
      cardShadow: '0 6px 24px rgba(8,145,178,0.12)',
      welcomeCardBgColor: '#ffffff',
      welcomeTextColor: '#0891b2',
      categoriesGridCols: '2',
    }
  },
  {
    id: 'modern-pizzeria',
    name: '🍕 Modern Pizzeria',
    description: 'Pizzería rápida de alta calidad. Rojo tomate vibrante y amarillo queso sobre fondo carbón. Grid de 2 columnas denso, botones llamativos. Rápido y apetitoso.',
    emoji: '🍕',
    previewBg: '#18120a',
    previewAccent: '#ef4444',
    previewCard: '#201810',
    config: {
      theme: 'dark',
      primaryColor: '#ef4444',
      backgroundColor: '#18120a',
      navBarBgColor: '#0e0a06',
      navBarTextColor: '#fef2f2',
      fontFamily: 'Outfit',
      fullWidthBackground: true,
      cardBackgroundColor: '#201810',
      cardBackgroundOpacity: '100',
      cardBlur: '0',
      showCardBorder: true,
      cardBorderWidth: '1',
      cardBorderColor: '#2c1f12',
      cardBorderRadius: '12',
      cardMarginTop: '0', cardMarginRight: '4', cardMarginBottom: '10', cardMarginLeft: '4',
      cardPaddingTop: '0', cardPaddingRight: '0', cardPaddingBottom: '12', cardPaddingLeft: '0',
      cardLayout: 'col-standard',
      gridColumns: '2',
      titleFontSize: '14',
      titleColor: '#fef2f2',
      titleUppercase: false,
      titleLetterSpacing: '0',
      descFontSize: '11',
      descColor: '#9a7a5a',
      priceFontSize: '15',
      priceColor: '#f59e0b',
      productImageWidth: '0',
      productImageRadius: '8px',
      productImageHeight: '130',
      cardSeparatorStyle: 'none',
      addButtonColor: '#ef4444',
      addButtonTextColor: '#ffffff',
      addButtonRadius: '8',
      addButtonWidth: '100',
      addButtonFontSize: '12',
      subcatFontSize: '18',
      subcatColor: '#ef4444',
      subcatAlignment: 'left',
      subcatBgColor: '#18120a',
      subcatTextColor: '#fef2f2',
      bgOverlayEnabled: false,
      showItemIndexBadge: false,
      categoryCardBgColor: '#201810',
      categoryCardTextColor: '#fef2f2',
      cardShadow: '0 4px 16px rgba(0,0,0,0.3)',
      welcomeCardBgColor: '#201810',
      welcomeTextColor: '#ef4444',
      categoriesGridCols: '2',
    }
  },
  {
    id: 'nordic-coffee-roasters',
    name: '🌲 Nordic Coffee Roasters',
    description: 'Café de especialidad y tostaduria escandinava. Blanco nórdico, gris humo y carbón mate. Minimalismo absoluto, grandes espacios vacíos y tipografía Inter condensada.',
    emoji: '🌲',
    previewBg: '#fafafa',
    previewAccent: '#292524',
    previewCard: '#ffffff',
    config: {
      theme: 'light',
      primaryColor: '#292524',
      backgroundColor: '#fafafa',
      navBarBgColor: '#ffffff',
      navBarTextColor: '#292524',
      fontFamily: 'Inter',
      fullWidthBackground: true,
      cardBackgroundColor: '#ffffff',
      cardBackgroundOpacity: '100',
      cardBlur: '0',
      showCardBorder: false,
      cardBorderRadius: '0',
      cardMarginTop: '0', cardMarginRight: '0', cardMarginBottom: '1', cardMarginLeft: '0',
      cardPaddingTop: '20', cardPaddingRight: '16', cardPaddingBottom: '20', cardPaddingLeft: '16',
      cardLayout: 'row-traditional',
      gridColumns: '1',
      titleFontSize: '15',
      titleColor: '#1c1917',
      titleUppercase: false,
      titleLetterSpacing: '0',
      descFontSize: '13',
      descColor: '#78716c',
      priceFontSize: '15',
      priceColor: '#292524',
      productImageWidth: '0',
      productImageRadius: '4px',
      productImageHeight: '70',
      cardSeparatorStyle: 'solid',
      cardSeparatorColor: '#e7e5e4',
      cardSeparatorHeight: '1',
      cardSeparatorWidth: '100',
      addButtonColor: '#292524',
      addButtonTextColor: '#fafafa',
      addButtonRadius: '4',
      addButtonWidth: 'auto',
      addButtonFontSize: '12',
      subcatFontSize: '13',
      subcatColor: '#78716c',
      subcatAlignment: 'left',
      subcatBgColor: '#fafafa',
      subcatTextColor: '#292524',
      bgOverlayEnabled: false,
      showItemIndexBadge: false,
      categoryCardBgColor: '#f5f5f4',
      categoryCardTextColor: '#1c1917',
      cardShadow: 'none',
      welcomeCardBgColor: '#ffffff',
      welcomeTextColor: '#292524',
      categoriesGridCols: '1',
    }
  },
  {
    id: 'sweet-pastel-gelateria',
    name: '🍦 Sweet Pastel Gelateria',
    description: 'Heladería, waffles y postres coloridos. Rosa chicle, verde menta y amarillo vainilla. Alegre, juguetón e irresistible para dulcerías y dessert bars.',
    emoji: '🍦',
    previewBg: '#fff0f6',
    previewAccent: '#ec4899',
    previewCard: '#ffffff',
    config: {
      theme: 'light',
      primaryColor: '#ec4899',
      backgroundColor: '#fff0f6',
      navBarBgColor: '#fce7f3',
      navBarTextColor: '#9d174d',
      fontFamily: 'Outfit',
      fullWidthBackground: true,
      cardBackgroundColor: '#ffffff',
      cardBackgroundOpacity: '100',
      cardBlur: '0',
      showCardBorder: true,
      cardBorderWidth: '2',
      cardBorderColor: '#fbcfe8',
      cardBorderRadius: '28',
      cardMarginTop: '0', cardMarginRight: '6', cardMarginBottom: '14', cardMarginLeft: '6',
      cardPaddingTop: '0', cardPaddingRight: '0', cardPaddingBottom: '14', cardPaddingLeft: '0',
      cardLayout: 'col-standard',
      gridColumns: '2',
      titleFontSize: '14',
      titleColor: '#831843',
      titleUppercase: false,
      titleLetterSpacing: '0',
      descFontSize: '11',
      descColor: '#be85a8',
      priceFontSize: '15',
      priceColor: '#ec4899',
      productImageWidth: '0',
      productImageRadius: '20px',
      productImageHeight: '135',
      cardSeparatorStyle: 'none',
      addButtonColor: '#ec4899',
      addButtonTextColor: '#ffffff',
      addButtonRadius: '50',
      addButtonWidth: '100',
      addButtonFontSize: '12',
      subcatFontSize: '18',
      subcatColor: '#9d174d',
      subcatAlignment: 'center',
      subcatBgColor: '#fce7f3',
      subcatTextColor: '#9d174d',
      bgOverlayEnabled: false,
      showItemIndexBadge: false,
      categoryCardBgColor: '#fce7f3',
      categoryCardTextColor: '#831843',
      cardShadow: '0 6px 20px rgba(236,72,153,0.12)',
      welcomeCardBgColor: '#ffffff',
      welcomeTextColor: '#ec4899',
      categoriesGridCols: '2',
    }
  },
  {
    id: 'vintage-mexican-cantina',
    name: '🌮 Vintage Mexican Cantina',
    description: 'Tacos, mezcal y comida auténtica mexicana. Naranja barro, verde cactus y amarillo sol. Cálido, festivo y lleno de sabor cultural.',
    emoji: '🌮',
    previewBg: '#1c0a00',
    previewAccent: '#ea580c',
    previewCard: '#2d1205',
    config: {
      theme: 'dark',
      primaryColor: '#ea580c',
      backgroundColor: '#1c0a00',
      navBarBgColor: '#1c0a00',
      navBarTextColor: '#fde68a',
      fontFamily: 'Lora',
      fullWidthBackground: true,
      cardBackgroundColor: '#2d1205',
      cardBackgroundOpacity: '100',
      cardBlur: '0',
      showCardBorder: true,
      cardBorderWidth: '1',
      cardBorderColor: '#3d1a08',
      cardBorderRadius: '10',
      cardMarginTop: '0', cardMarginRight: '4', cardMarginBottom: '12', cardMarginLeft: '4',
      cardPaddingTop: '0', cardPaddingRight: '0', cardPaddingBottom: '12', cardPaddingLeft: '0',
      cardLayout: 'col-standard',
      gridColumns: '2',
      titleFontSize: '15',
      titleColor: '#fde68a',
      titleUppercase: false,
      titleLetterSpacing: '0',
      descFontSize: '12',
      descColor: '#c4854a',
      priceFontSize: '15',
      priceColor: '#ea580c',
      productImageWidth: '0',
      productImageRadius: '8px',
      productImageHeight: '140',
      cardSeparatorStyle: 'none',
      addButtonColor: '#ea580c',
      addButtonTextColor: '#1c0a00',
      addButtonRadius: '8',
      addButtonWidth: '100',
      addButtonFontSize: '12',
      subcatFontSize: '20',
      subcatColor: '#ea580c',
      subcatAlignment: 'left',
      subcatBgColor: '#1c0a00',
      subcatTextColor: '#fde68a',
      bgOverlayEnabled: false,
      showItemIndexBadge: false,
      categoryCardBgColor: '#2d1205',
      categoryCardTextColor: '#fde68a',
      cardShadow: '0 4px 16px rgba(0,0,0,0.4)',
      welcomeCardBgColor: '#2d1205',
      welcomeTextColor: '#ea580c',
      categoriesGridCols: '2',
    }
  },
  {
    id: 'royal-tea-room',
    name: '👑 Royal Tea Room',
    description: 'Salón de té y pastelería fina estilo inglés. Azul empolvado, rosa dorado y blanco seda. Elegancia palaciega con glassmorphism ultra-suave.',
    emoji: '👑',
    previewBg: '#f0f4ff',
    previewAccent: '#7c3aed',
    previewCard: '#ffffff',
    config: {
      theme: 'light',
      primaryColor: '#7c3aed',
      backgroundColor: '#f0f4ff',
      navBarBgColor: '#ede9fe',
      navBarTextColor: '#4c1d95',
      fontFamily: 'Playfair Display',
      fullWidthBackground: true,
      cardBackgroundColor: '#ffffff',
      cardBackgroundOpacity: '90',
      cardBlur: '8',
      showCardBorder: true,
      cardBorderWidth: '1',
      cardBorderColor: '#ddd6fe',
      cardBorderRadius: '20',
      cardMarginTop: '0', cardMarginRight: '6', cardMarginBottom: '16', cardMarginLeft: '6',
      cardPaddingTop: '0', cardPaddingRight: '0', cardPaddingBottom: '14', cardPaddingLeft: '0',
      cardLayout: 'col-standard',
      gridColumns: '2',
      titleFontSize: '15',
      titleColor: '#2e1065',
      titleUppercase: false,
      titleLetterSpacing: '0.02',
      descFontSize: '12',
      descColor: '#7e6ca8',
      priceFontSize: '15',
      priceColor: '#7c3aed',
      productImageWidth: '0',
      productImageRadius: '16px',
      productImageHeight: '140',
      cardSeparatorStyle: 'none',
      addButtonColor: '#7c3aed',
      addButtonTextColor: '#ffffff',
      addButtonRadius: '50',
      addButtonWidth: '100',
      addButtonFontSize: '12',
      subcatFontSize: '18',
      subcatColor: '#4c1d95',
      subcatAlignment: 'center',
      subcatBgColor: '#ede9fe',
      subcatTextColor: '#4c1d95',
      bgOverlayEnabled: false,
      showItemIndexBadge: false,
      categoryCardBgColor: '#ede9fe',
      categoryCardTextColor: '#2e1065',
      cardShadow: '0 4px 20px rgba(124,58,237,0.1)',
      welcomeCardBgColor: '#ffffff',
      welcomeTextColor: '#7c3aed',
      categoriesGridCols: '2',
    }
  },
  {
    id: 'futuristic-gastropub',
    name: '🛸 Futuristic Gastropub',
    description: 'Gastropub moderno y tecnológico. Carbono oscuro con detalles plateados y acero azul. Líneas ultra-limpias, bordes metálicos y estética industrial futurista.',
    emoji: '🛸',
    previewBg: '#080c10',
    previewAccent: '#38bdf8',
    previewCard: '#0f1520',
    config: {
      theme: 'dark',
      primaryColor: '#38bdf8',
      backgroundColor: '#080c10',
      navBarBgColor: '#040608',
      navBarTextColor: '#e2e8f0',
      fontFamily: 'Outfit',
      fullWidthBackground: true,
      cardBackgroundColor: '#0f1520',
      cardBackgroundOpacity: '100',
      cardBlur: '0',
      showCardBorder: true,
      cardBorderWidth: '1',
      cardBorderColor: '#1e293b',
      cardBorderRadius: '6',
      cardMarginTop: '0', cardMarginRight: '0', cardMarginBottom: '12', cardMarginLeft: '0',
      cardPaddingTop: '16', cardPaddingRight: '16', cardPaddingBottom: '16', cardPaddingLeft: '16',
      cardLayout: 'row-img-left',
      gridColumns: '1',
      titleFontSize: '16',
      titleColor: '#e2e8f0',
      titleUppercase: true,
      titleLetterSpacing: '0.06',
      descFontSize: '12',
      descColor: '#475569',
      priceFontSize: '16',
      priceColor: '#38bdf8',
      productImageWidth: '0',
      productImageRadius: '4px',
      productImageHeight: '85',
      cardSeparatorStyle: 'none',
      addButtonColor: '#38bdf8',
      addButtonTextColor: '#080c10',
      addButtonRadius: '4',
      addButtonWidth: 'auto',
      addButtonFontSize: '12',
      subcatFontSize: '14',
      subcatColor: '#38bdf8',
      subcatAlignment: 'left',
      subcatBgColor: '#080c10',
      subcatTextColor: '#94a3b8',
      bgOverlayEnabled: false,
      showItemIndexBadge: false,
      categoryCardBgColor: '#0f1520',
      categoryCardTextColor: '#e2e8f0',
      cardShadow: '0 4px 24px rgba(0,0,0,0.5)',
      welcomeCardBgColor: '#0f1520',
      welcomeTextColor: '#38bdf8',
      categoriesGridCols: '2',
    }
  },
  {
    id: 'fauget-classic',
    name: '🖼️ Fauget Classic',
    description: 'Elegancia editorial con foto circular a la izquierda y texto enmarcado. Diseño tipo revista de gastronomía, con fondo crema, acento verde botella y bordes lineales refinados.',
    emoji: '🖼️',
    previewBg: '#faf7f2',
    previewAccent: '#3d6b4f',
    previewCard: '#ffffff',
    config: {
      theme: 'light',
      primaryColor: '#3d6b4f',
      backgroundColor: '#faf7f2',
      navBarBgColor: '#1a2e22',
      navBarTextColor: '#f0ebe0',
      fontFamily: 'Lora',
      fullWidthBackground: true,
      cardBackgroundColor: '#ffffff',
      cardBackgroundOpacity: '0',
      cardBlur: '0',
      showCardBorder: false,
      cardBorderWidth: '0',
      cardBorderColor: '#3d6b4f',
      cardBorderRadius: '0',
      cardMarginTop: '0', cardMarginRight: '0', cardMarginBottom: '24', cardMarginLeft: '0',
      cardPaddingTop: '0', cardPaddingRight: '0', cardPaddingBottom: '0', cardPaddingLeft: '0',
      cardLayout: 'row-offset-border',
      gridColumns: '1',
      titleFontSize: '18',
      titleColor: '#1a2e22',
      titleUppercase: false,
      titleLetterSpacing: '0',
      descFontSize: '13',
      descColor: '#5a6b60',
      priceFontSize: '17',
      priceColor: '#3d6b4f',
      priceLetterSpacing: '0',
      productImageWidth: '0',
      productImageRadius: '50%',
      productImageHeight: '130',
      cardSeparatorStyle: 'none',
      addButtonColor: '#3d6b4f',
      addButtonTextColor: '#ffffff',
      addButtonRadius: '0',
      addButtonWidth: 'auto',
      addButtonFontSize: '13',
      subcatFontSize: '13',
      subcatColor: '#3d6b4f',
      subcatAlignment: 'left',
      subcatBgColor: '#faf7f2',
      subcatTextColor: '#3d6b4f',
      bgOverlayEnabled: false,
      showItemIndexBadge: false,
      categoryCardBgColor: '#f0ebe0',
      categoryCardTextColor: '#1a2e22',
      cardShadow: 'none',
      welcomeCardBgColor: '#ffffff',
      welcomeTextColor: '#3d6b4f',
      categoriesGridCols: '2',
    }
  },
  {
    id: 'fauget-zigzag',
    name: '⚡ Fauget Zigzag',
    description: 'Disposición escalonada impactante: los productos alternan foto izquierda / foto derecha creando un ritmo visual dinámico. Fondo oscuro profundo con acento naranja quemado, ideal para menús creativos y urbanos.',
    emoji: '⚡',
    previewBg: '#141010',
    previewAccent: '#e07b39',
    previewCard: '#1e1810',
    config: {
      theme: 'dark',
      primaryColor: '#e07b39',
      backgroundColor: '#141010',
      navBarBgColor: '#0d0b08',
      navBarTextColor: '#e07b39',
      fontFamily: 'Raleway',
      fullWidthBackground: true,
      cardBackgroundColor: '#1e1810',
      cardBackgroundOpacity: '0',
      cardBlur: '0',
      showCardBorder: false,
      cardBorderWidth: '0',
      cardBorderColor: '#e07b39',
      cardBorderRadius: '0',
      cardMarginTop: '0', cardMarginRight: '0', cardMarginBottom: '28', cardMarginLeft: '0',
      cardPaddingTop: '0', cardPaddingRight: '0', cardPaddingBottom: '0', cardPaddingLeft: '0',
      cardLayout: 'row-offset-border-alt',
      gridColumns: '1',
      titleFontSize: '19',
      titleColor: '#f5ede0',
      titleUppercase: true,
      titleLetterSpacing: '0.05',
      descFontSize: '12',
      descColor: '#9a8a78',
      priceFontSize: '17',
      priceColor: '#e07b39',
      priceLetterSpacing: '0.05',
      productImageWidth: '0',
      productImageRadius: '50%',
      productImageHeight: '130',
      cardSeparatorStyle: 'none',
      addButtonColor: '#e07b39',
      addButtonTextColor: '#141010',
      addButtonRadius: '0',
      addButtonWidth: 'auto',
      addButtonFontSize: '12',
      subcatFontSize: '12',
      subcatColor: '#e07b39',
      subcatAlignment: 'left',
      subcatBgColor: '#141010',
      subcatTextColor: '#e07b39',
      bgOverlayEnabled: false,
      showItemIndexBadge: false,
      categoryCardBgColor: '#1e1810',
      categoryCardTextColor: '#f5ede0',
      cardShadow: 'none',
      welcomeCardBgColor: '#1e1810',
      welcomeTextColor: '#e07b39',
      categoriesGridCols: '2',
    }
  },
  {
    id: 'fauget-inverse',
    name: '🖼️ Fauget Inverso',
    description: 'Variante del estilo editorial con foto circular a la derecha y texto enmarcado. Diseño equilibrado con fondo crema, acento verde botella y bordes refinados.',
    emoji: '🖼️',
    previewBg: '#faf7f2',
    previewAccent: '#3d6b4f',
    previewCard: '#ffffff',
    config: {
      theme: 'light',
      primaryColor: '#3d6b4f',
      backgroundColor: '#faf7f2',
      navBarBgColor: '#1a2e22',
      navBarTextColor: '#f0ebe0',
      fontFamily: 'Lora',
      fullWidthBackground: true,
      cardBackgroundColor: '#ffffff',
      cardBackgroundOpacity: '0',
      cardBlur: '0',
      showCardBorder: false,
      cardBorderWidth: '0',
      cardBorderColor: '#3d6b4f',
      cardBorderRadius: '0',
      cardMarginTop: '0', cardMarginRight: '0', cardMarginBottom: '24', cardMarginLeft: '0',
      cardPaddingTop: '0', cardPaddingRight: '0', cardPaddingBottom: '0', cardPaddingLeft: '0',
      cardLayout: 'row-offset-border-r',
      gridColumns: '1',
      titleFontSize: '18',
      titleColor: '#1a2e22',
      titleUppercase: false,
      titleLetterSpacing: '0',
      descFontSize: '13',
      descColor: '#5a6b60',
      priceFontSize: '17',
      priceColor: '#3d6b4f',
      priceLetterSpacing: '0',
      productImageWidth: '0',
      productImageRadius: '50%',
      productImageHeight: '130',
      cardSeparatorStyle: 'none',
      addButtonColor: '#3d6b4f',
      addButtonTextColor: '#ffffff',
      addButtonRadius: '0',
      addButtonWidth: 'auto',
      addButtonFontSize: '13',
      subcatFontSize: '13',
      subcatColor: '#3d6b4f',
      subcatAlignment: 'left',
      subcatBgColor: '#faf7f2',
      subcatTextColor: '#3d6b4f',
      bgOverlayEnabled: false,
      showItemIndexBadge: false,
      categoryCardBgColor: '#f0ebe0',
      categoryCardTextColor: '#1a2e22',
      cardShadow: 'none',
      welcomeCardBgColor: '#ffffff',
      welcomeTextColor: '#3d6b4f',
      categoriesGridCols: '2',
    }
  },
  {
    id: 'fauget-zigzag-inverse',
    name: '⚡ Fauget Zigzag Inverso',
    description: 'Variante escalonada donde el primer producto tiene la foto a la derecha y el siguiente a la izquierda. Fondo oscuro con acento naranja quemado.',
    emoji: '⚡',
    previewBg: '#141010',
    previewAccent: '#e07b39',
    previewCard: '#1e1810',
    config: {
      theme: 'dark',
      primaryColor: '#e07b39',
      backgroundColor: '#141010',
      navBarBgColor: '#0d0b08',
      navBarTextColor: '#e07b39',
      fontFamily: 'Raleway',
      fullWidthBackground: true,
      cardBackgroundColor: '#1e1810',
      cardBackgroundOpacity: '0',
      cardBlur: '0',
      showCardBorder: false,
      cardBorderWidth: '0',
      cardBorderColor: '#e07b39',
      cardBorderRadius: '0',
      cardMarginTop: '0', cardMarginRight: '0', cardMarginBottom: '28', cardMarginLeft: '0',
      cardPaddingTop: '0', cardPaddingRight: '0', cardPaddingBottom: '0', cardPaddingLeft: '0',
      cardLayout: 'row-offset-border-alt-r',
      gridColumns: '1',
      titleFontSize: '19',
      titleColor: '#f5ede0',
      titleUppercase: true,
      titleLetterSpacing: '0.05',
      descFontSize: '12',
      descColor: '#9a8a78',
      priceFontSize: '17',
      priceColor: '#e07b39',
      priceLetterSpacing: '0.05',
      productImageWidth: '0',
      productImageRadius: '50%',
      productImageHeight: '130',
      cardSeparatorStyle: 'none',
      addButtonColor: '#e07b39',
      addButtonTextColor: '#141010',
      addButtonRadius: '0',
      addButtonWidth: 'auto',
      addButtonFontSize: '12',
      subcatFontSize: '12',
      subcatColor: '#e07b39',
      subcatAlignment: 'left',
      subcatBgColor: '#141010',
      subcatTextColor: '#e07b39',
      bgOverlayEnabled: false,
      showItemIndexBadge: false,
      categoryCardBgColor: '#1e1810',
      categoryCardTextColor: '#f5ede0',
      cardShadow: 'none',
      welcomeCardBgColor: '#1e1810',
      welcomeTextColor: '#e07b39',
      categoriesGridCols: '2',
    }
  },
];
