export const THEMES = [
  {
    id: 'noir-luxe',
    name: '🖤 Noir Luxe (Alta Costura)',
    description: 'Diseño editorial oscuro de alta gama. Inspirado en Balenciaga y Rick Owens. Fondo negro carbón profundo con acentos en marfil y oro mate. Excelente para marcas de ropa exclusivas y accesorios premium.',
    emoji: '🖤',
    previewBg: '#0a0a0c',
    previewAccent: '#c9a84c',
    previewCard: '#141318',
    config: {
      theme: 'dark',
      primaryColor: '#c9a84c',
      backgroundColor: '#0a0a0c',
      navBarBgColor: '#0a0a0c',
      navBarTextColor: '#c9a84c',
      fontFamily: 'Playfair Display',
      fullWidthBackground: true,
      cardBackgroundColor: '#141318',
      cardBackgroundOpacity: '100',
      cardBlur: '0',
      showCardBorder: true,
      cardBorderWidth: '1',
      cardBorderColor: '#2a2318',
      cardBorderRadius: '0',
      cardMarginTop: '0', cardMarginRight: '0', cardMarginBottom: '16', cardMarginLeft: '0',
      cardPaddingTop: '0', cardPaddingRight: '0', cardPaddingBottom: '12', cardPaddingLeft: '0',
      cardLayout: 'col-standard',
      gridColumns: '2',
      titleFontSize: '14',
      titleColor: '#f5f0e8',
      titleUppercase: true,
      titleLetterSpacing: '0.1',
      descFontSize: '11',
      descColor: '#8a7e6a',
      priceFontSize: '14',
      priceColor: '#c9a84c',
      productImageHeight: '180',
      addButtonColor: '#c9a84c',
      addButtonTextColor: '#0a0a0c',
      addButtonRadius: '0',
      addButtonWidth: '100',
      addButtonFontSize: '11',
      subcatFontSize: '14',
      subcatColor: '#c9a84c',
      subcatAlignment: 'center',
      subcatBgColor: '#141318',
      subcatTextColor: '#c9a84c',
      cardShadow: 'none',
      welcomeCardBgColor: '#141318',
      welcomeTextColor: '#c9a84c',
      categoriesGridCols: '2',
      ecommerceMode: true,
      ecommerceSettings: {
        homeLayout: 'noir'
      }
    }
  },
  {
    id: 'urban-street',
    name: '🔴 Urban Street (Streetwear)',
    description: 'Estilo urbano enérgico y moderno. Inspirado en Supreme y Off-White. Tipografía Space Grotesk, fondo crema urbano con acentos en negro y rojo vibrante. Perfecto para calzado, gorras y streetwear.',
    emoji: '🔴',
    previewBg: '#f2f0eb',
    previewAccent: '#e5131a',
    previewCard: '#ffffff',
    config: {
      theme: 'light',
      primaryColor: '#e5131a',
      backgroundColor: '#f2f0eb',
      navBarBgColor: '#0d0d0d',
      navBarTextColor: '#f2f0eb',
      fontFamily: 'Outfit',
      fullWidthBackground: true,
      cardBackgroundColor: '#ffffff',
      cardBackgroundOpacity: '100',
      cardBlur: '0',
      showCardBorder: true,
      cardBorderWidth: '2',
      cardBorderColor: '#0d0d0d',
      cardBorderRadius: '0',
      cardMarginTop: '0', cardMarginRight: '4', cardMarginBottom: '14', cardMarginLeft: '4',
      cardPaddingTop: '0', cardPaddingRight: '0', cardPaddingBottom: '12', cardPaddingLeft: '0',
      cardLayout: 'col-standard',
      gridColumns: '2',
      titleFontSize: '14',
      titleColor: '#0d0d0d',
      titleUppercase: true,
      titleLetterSpacing: '0.05',
      descFontSize: '11',
      descColor: '#5a5a5a',
      priceFontSize: '15',
      priceColor: '#e5131a',
      productImageHeight: '190',
      addButtonColor: '#0d0d0d',
      addButtonTextColor: '#f2f0eb',
      addButtonRadius: '0',
      addButtonWidth: '100',
      addButtonFontSize: '12',
      subcatFontSize: '14',
      subcatColor: '#0d0d0d',
      subcatAlignment: 'left',
      subcatBgColor: '#ffffff',
      subcatTextColor: '#0d0d0d',
      cardShadow: '6px 6px 0 #0d0d0d',
      welcomeCardBgColor: '#ffffff',
      welcomeTextColor: '#0d0d0d',
      categoriesGridCols: '2',
      ecommerceMode: true,
      ecommerceSettings: {
        homeLayout: 'urban'
      }
    }
  },
  {
    id: 'bloom-boutique',
    name: '🌸 Bloom Boutique (Femenino)',
    description: 'Estilo suave, elegante y orgánico. Inspirado en Zara Woman y marcas boutique independientes. Tipografía serif Playfair Display, fondo arena suave con tonos tierra cálidos. Ideal para moda femenina y joyería.',
    emoji: '🌸',
    previewBg: '#faf8f5',
    previewAccent: '#9a7060',
    previewCard: '#ffffff',
    config: {
      theme: 'light',
      primaryColor: '#9a7060',
      backgroundColor: '#faf8f5',
      navBarBgColor: '#ffffff',
      navBarTextColor: '#2c2c2c',
      fontFamily: 'Lora',
      fullWidthBackground: true,
      cardBackgroundColor: '#ffffff',
      cardBackgroundOpacity: '100',
      cardBlur: '0',
      showCardBorder: false,
      cardBorderRadius: '4',
      cardMarginTop: '0', cardMarginRight: '6', cardMarginBottom: '14', cardMarginLeft: '6',
      cardPaddingTop: '0', cardPaddingRight: '0', cardPaddingBottom: '12', cardPaddingLeft: '0',
      cardLayout: 'col-standard',
      gridColumns: '3',
      titleFontSize: '14',
      titleColor: '#2c2c2c',
      titleUppercase: false,
      titleLetterSpacing: '0',
      descFontSize: '11',
      descColor: '#8a7a72',
      priceFontSize: '14',
      priceColor: '#9a7060',
      productImageHeight: '180',
      addButtonColor: '#9a7060',
      addButtonTextColor: '#faf8f5',
      addButtonRadius: '2',
      addButtonWidth: '100',
      addButtonFontSize: '11',
      subcatFontSize: '14',
      subcatColor: '#9a7060',
      subcatAlignment: 'center',
      subcatBgColor: '#ffffff',
      subcatTextColor: '#2c2c2c',
      cardShadow: '0 4px 12px rgba(154,112,96,0.05)',
      welcomeCardBgColor: '#ffffff',
      welcomeTextColor: '#2c2c2c',
      categoriesGridCols: '2',
      ecommerceMode: true,
      ecommerceSettings: {
        homeLayout: 'bloom'
      }
    }
  },
  {
    id: 'minimalist-boutique',
    name: '🧥 Minimalist Boutique',
    description: 'Moda y prendas de vestir limpia. Blanco puro, acento negro carbón, tipografía Outfit condensada. Un clásico moderno para cualquier tipo de catálogo retail.',
    emoji: '🧥',
    previewBg: '#fafafa',
    previewAccent: '#111111',
    previewCard: '#ffffff',
    config: {
      theme: 'light',
      primaryColor: '#111111',
      backgroundColor: '#fafafa',
      navBarBgColor: '#ffffff',
      navBarTextColor: '#111111',
      fontFamily: 'Outfit',
      fullWidthBackground: true,
      cardBackgroundColor: '#ffffff',
      cardBackgroundOpacity: '100',
      cardBlur: '0',
      showCardBorder: false,
      cardBorderRadius: '8',
      cardMarginTop: '0', cardMarginRight: '4', cardMarginBottom: '12', cardMarginLeft: '4',
      cardPaddingTop: '0', cardPaddingRight: '0', cardPaddingBottom: '10', cardPaddingLeft: '0',
      cardLayout: 'col-standard',
      gridColumns: '2',
      titleFontSize: '14',
      titleColor: '#111111',
      titleUppercase: false,
      titleLetterSpacing: '0',
      descFontSize: '11',
      descColor: '#767676',
      priceFontSize: '14',
      priceColor: '#111111',
      productImageHeight: '180',
      addButtonColor: '#111111',
      addButtonTextColor: '#ffffff',
      addButtonRadius: '4',
      addButtonWidth: '100',
      addButtonFontSize: '11',
      subcatFontSize: '14',
      subcatColor: '#111111',
      subcatAlignment: 'center',
      subcatBgColor: '#ffffff',
      subcatTextColor: '#111111',
      cardShadow: '0 2px 8px rgba(0,0,0,0.04)',
      welcomeCardBgColor: '#ffffff',
      welcomeTextColor: '#111111',
      categoriesGridCols: '2',
      ecommerceMode: true,
      ecommerceSettings: {
        homeLayout: 'minimal'
      }
    }
  },
  {
    id: 'classic-store',
    name: '🏠 Classic Store (Multiuso)',
    description: 'Diseño clásico multiuso. Con carrusel superior configurable, vitrina de categorías e información inferior de mapa y sedes. Excelente para tiendas que requieren mucha personalización.',
    emoji: '🏠',
    previewBg: '#f8fafc',
    previewAccent: '#2563eb',
    previewCard: '#ffffff',
    config: {
      theme: 'light',
      primaryColor: '#2563eb',
      backgroundColor: '#f8fafc',
      navBarBgColor: '#ffffff',
      navBarTextColor: '#1e293b',
      fontFamily: 'Inter',
      fullWidthBackground: true,
      cardBackgroundColor: '#ffffff',
      cardBackgroundOpacity: '100',
      cardBlur: '0',
      showCardBorder: false,
      cardBorderRadius: '12',
      cardMarginTop: '0', cardMarginRight: '6', cardMarginBottom: '14', cardMarginLeft: '6',
      cardPaddingTop: '0', cardPaddingRight: '0', cardPaddingBottom: '12', cardPaddingLeft: '0',
      cardLayout: 'col-standard',
      gridColumns: '2',
      titleFontSize: '14',
      titleColor: '#1e293b',
      titleUppercase: false,
      titleLetterSpacing: '0',
      descFontSize: '11',
      descColor: '#64748b',
      priceFontSize: '14',
      priceColor: '#2563eb',
      productImageHeight: '160',
      addButtonColor: '#2563eb',
      addButtonTextColor: '#ffffff',
      addButtonRadius: '8',
      addButtonWidth: '100',
      addButtonFontSize: '11',
      subcatFontSize: '14',
      subcatColor: '#2563eb',
      subcatAlignment: 'center',
      subcatBgColor: '#ffffff',
      subcatTextColor: '#1e293b',
      cardShadow: '0 4px 12px rgba(37,99,235,0.03)',
      welcomeCardBgColor: '#ffffff',
      welcomeTextColor: '#2563eb',
      categoriesGridCols: '2',
      ecommerceMode: true,
      ecommerceSettings: {
        homeLayout: 'classic'
      }
    }
  }
];
